// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCQdm6UjpCDR4gUSOGXbwxsSvNZr34kY',
    appId: '1:145282306101:android:357e0ecf81590e2843a17c',
    messagingSenderId: '145282306101',
    projectId: 'my-tube-list-6fec2',
    authDomain: 'my-tube-list-6fec2.firebaseapp.com',
    storageBucket: 'my-tube-list-6fec2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCQdm6UjpCDR4gUSOGXbwxsSvNZr34kY',
    appId: '1:145282306101:android:357e0ecf81590e2843a17c',
    messagingSenderId: '145282306101',
    projectId: 'my-tube-list-6fec2',
    databaseURL: 'https://my-tube-list-6fec2-default-rtdb.firebaseio.com',
    storageBucket: 'my-tube-list-6fec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPCQdm6UjpCDR4gUSOGXbwxsSvNZr34kY',
    appId: '1:145282306101:android:357e0ecf81590e2843a17c',
    messagingSenderId: '145282306101',
    projectId: 'my-tube-list-6fec2',
    storageBucket: 'my-tube-list-6fec2.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.myTubeList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPCQdm6UjpCDR4gUSOGXbwxsSvNZr34kY',
    appId: '1:145282306101:android:357e0ecf81590e2843a17c',
    messagingSenderId: '145282306101',
    projectId: 'my-tube-list-6fec2',
    storageBucket: 'my-tube-list-6fec2.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.myTubeList',
  );
}